# Generated by Django 5.1.7 on 2025-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchmart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
