# Generated by Django 5.1.7 on 2025-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchmart', '0002_alter_groceryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='company',
            field=models.CharField(default='Local Mart', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='review',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
