# Generated by Django 5.1.4 on 2025-04-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munchmart', '0004_groceryitem_type_userinfo_orderhistory_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='gst',
            new_name='total_gst',
        ),
    ]
