# Generated by Django 5.1.7 on 2025-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchmart', '0005_rename_gst_cart_total_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
